name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - workflow-test

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '20'
          submodules: true
          lfs: false
        # 新增：设置 Node 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
        # add clean build
      - name: Clean Node Modules & Build 
        run: |
          rm -rf node_modules build
          npm install
          npm run build
        env:
          REACT_APP_API_BASE_UPLOADS: ${{ secrets.REACT_APP_API_BASE_UPLOADS }}
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}

       # Ensure the configuration file is in the build/ directory
      - name: Copy staticwebapp.config.json to build
        run: cp ./react-lovelyfish/public/staticwebapp.config.json ./react-lovelyfish/build/

      # Debug: List the contents of the build directory
      - name: List build folder
        run: ls -l ./react-lovelyfish/build
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_MEADOW_0F44D3E00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./react-lovelyfish" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
        env:
          CI: false  # 忽略 ESLint 警告
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_MEADOW_0F44D3E00 }}
          action: "close"






