- name: Build And Deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_COAST_0E9E19400 }}
    action: "upload"
    app_location: "react-lovelyfish"   # React 源码目录
    output_location: "build"           # 相对 app_location，不要再写全路径
